apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-secret
  namespace: myapp
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: clustersecretstore
    kind: ClusterSecretStore
  target:
    name: postgres-secret # Name of the Kubernetes Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: User-data-CI # Name of the secret in AWS Secrets Manager
